<?php

namespace OffreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use UserBundle\Entity\Skill;

/**
 * SkillOffreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkillOffreRepository extends EntityRepository
{
   
}
