<?php

namespace OffreBundle\Repository;

/**
 * SkillOffreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkillOffreRepository extends \Doctrine\ORM\EntityRepository
{
}
