<?php

namespace ViewBundle\Repository;

/**
 * CommentCaMarcheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentCaMarcheRepository extends \Doctrine\ORM\EntityRepository
{
}
