<?php

namespace UserBundle\Repository;

/**
 * ListeDeSkillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListeDeSkillRepository extends \Doctrine\ORM\EntityRepository
{
}
