<?php

namespace UserBundle\Repository;

/**
 * RecruteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecruteurRepository extends \Doctrine\ORM\EntityRepository
{
}
