<?php

namespace UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SkillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkillRepository extends EntityRepository
{
     public function listSkills($listeSkills){
        $listeSkillsUp = array ();
           for($i=0;$i <= sizeof($listeSkills)-1;$i++){
                array_push($listeSkillsUp, $this->find($listeSkills[$i]));
           }
        
        return $listeSkillsUp ;
    }
}
